export type RootStackParamList = {
  Welcome: undefined;
  CreateAccount: undefined;
  SignIn: undefined;
  ForgotPassword: undefined;
  CheckEmail: { email: string; mode: 'signup' | 'reset' };
  ChooseRole: { userId: string };
  Specialty: undefined;
  BusinessDetails: undefined;
  ServicesAndPricing: undefined;
  Availability: undefined;
  Portfolio: undefined;
  ConnectPayouts: undefined;
  Membership: undefined;
  PromoUnlocked: undefined;
  ProAllSet: undefined;
  ProHome: undefined;
  Earnings: undefined;
  ClientHome: undefined;
  Map: undefined;
  ProProfile: undefined;
  PickTime: undefined;
  CancellationPolicy: undefined;
  ConfirmBooking: undefined;
  Chat: undefined;
  AddTip: undefined;
  RatePro: undefined;
  DeleteAccount: undefined;
  PrivacyPolicy: undefined;
  TermsOfService: undefined;
};
