export type RootStackParamList = {
  Welcome: undefined;
  CreateAccount: undefined;
  EnterPhone: { userId: string };
  VerifyPhone: { userId: string; phone: string };
  ChooseRole: { userId: string };
  Specialty: undefined;
  BusinessDetails: undefined;
  ServicesAndPricing: undefined;
  Availability: undefined;
  Portfolio: undefined;
  ConnectPayouts: undefined;
  Membership: undefined;
  PromoUnlocked: undefined;
  ProAllSet: undefined;
  ProHome: undefined;
  Earnings: undefined;
  ClientSignUp: undefined;
  ClientHome: undefined;
  ProProfile: undefined;
  PickTime: undefined;
  CancellationPolicy: undefined;
  ConfirmBooking: undefined;
  Chat: undefined;
  AddTip: undefined;
  RatePro: undefined;
};
